

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	int32_t capacity;
	int32_t len;
	uint8_t *data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

// Task defined in Rust that Go executes
typedef void (*RustTaskCallback)(const void *, int8_t);

// Callback to execute Rust tasks using a Go routine
//
// Args:
//   executor: ForeignExecutor lowered into a uint64_t value
//   delay: Delay in MS
//   task: RustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*ForeignExecutorCallback)(uint64_t, uint32_t, RustTaskCallback, void *);

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

// Continuation callback for UniFFI Futures
typedef void (*RustFutureContinuation)(void * , int8_t);

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Needed because we can't execute the callback directly from go.
void cgo_rust_task_callback_bridge_ldk_node(RustTaskCallback, const void *, int8_t);

int8_t uniffiForeignExecutorCallbackldk_node(uint64_t, uint32_t, RustTaskCallback, void*);

void uniffiFutureContinuationCallbackldk_node(void*, int8_t);

void uniffi_ldk_node_fn_free_bolt11payment(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_bolt11payment_claim_for_hash(
	void* ptr,
	RustBuffer payment_hash,
	uint64_t claimable_amount_msat,
	RustBuffer preimage,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_bolt11payment_fail_for_hash(
	void* ptr,
	RustBuffer payment_hash,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_receive(
	void* ptr,
	uint64_t amount_msat,
	RustBuffer description,
	uint32_t expiry_secs,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_receive_for_hash(
	void* ptr,
	uint64_t amount_msat,
	RustBuffer description,
	uint32_t expiry_secs,
	RustBuffer payment_hash,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_receive_variable_amount(
	void* ptr,
	RustBuffer description,
	uint32_t expiry_secs,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_receive_variable_amount_for_hash(
	void* ptr,
	RustBuffer description,
	uint32_t expiry_secs,
	RustBuffer payment_hash,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_receive_variable_amount_via_jit_channel(
	void* ptr,
	RustBuffer description,
	uint32_t expiry_secs,
	RustBuffer max_proportional_lsp_fee_limit_ppm_msat,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_receive_via_jit_channel(
	void* ptr,
	uint64_t amount_msat,
	RustBuffer description,
	uint32_t expiry_secs,
	RustBuffer max_lsp_fee_limit_msat,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_send(
	void* ptr,
	RustBuffer invoice,
	RustBuffer sending_parameters,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_bolt11payment_send_probes(
	void* ptr,
	RustBuffer invoice,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_bolt11payment_send_probes_using_amount(
	void* ptr,
	RustBuffer invoice,
	uint64_t amount_msat,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt11payment_send_using_amount(
	void* ptr,
	RustBuffer invoice,
	uint64_t amount_msat,
	RustBuffer sending_parameters,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_free_bolt12payment(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt12payment_initiate_refund(
	void* ptr,
	uint64_t amount_msat,
	uint32_t expiry_secs,
	RustBuffer quantity,
	RustBuffer payer_note,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt12payment_receive(
	void* ptr,
	uint64_t amount_msat,
	RustBuffer description,
	RustBuffer expiry_secs,
	RustBuffer quantity,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt12payment_receive_variable_amount(
	void* ptr,
	RustBuffer description,
	RustBuffer expiry_secs,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt12payment_request_refund_payment(
	void* ptr,
	RustBuffer refund,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt12payment_send(
	void* ptr,
	RustBuffer offer,
	RustBuffer quantity,
	RustBuffer payer_note,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_bolt12payment_send_using_amount(
	void* ptr,
	RustBuffer offer,
	uint64_t amount_msat,
	RustBuffer quantity,
	RustBuffer payer_note,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_free_builder(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_constructor_builder_from_config(
	RustBuffer config,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_constructor_builder_new(
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_builder_build(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_builder_build_with_fs_store(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_builder_build_with_vss_store(
	void* ptr,
	RustBuffer vss_url,
	RustBuffer store_id,
	RustBuffer lnurl_auth_server_url,
	RustBuffer fixed_headers,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_builder_build_with_vss_store_and_fixed_headers(
	void* ptr,
	RustBuffer vss_url,
	RustBuffer store_id,
	RustBuffer fixed_headers,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_migrate_storage(
	void* ptr,
	RustBuffer what,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_reset_state(
	void* ptr,
	RustBuffer what,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_restore_encoded_channel_monitors(
	void* ptr,
	RustBuffer monitors,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_chain_source_bitcoind_rpc(
	void* ptr,
	RustBuffer rpc_host,
	uint16_t rpc_port,
	RustBuffer rpc_user,
	RustBuffer rpc_password,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_chain_source_esplora(
	void* ptr,
	RustBuffer server_url,
	RustBuffer config,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_entropy_bip39_mnemonic(
	void* ptr,
	RustBuffer mnemonic,
	RustBuffer passphrase,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_entropy_seed_bytes(
	void* ptr,
	RustBuffer seed_bytes,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_entropy_seed_path(
	void* ptr,
	RustBuffer seed_path,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_gossip_source_p2p(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_gossip_source_rgs(
	void* ptr,
	RustBuffer rgs_server_url,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_liquidity_source_lsps2(
	void* ptr,
	RustBuffer address,
	RustBuffer node_id,
	RustBuffer token,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_listening_addresses(
	void* ptr,
	RustBuffer listening_addresses,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_network(
	void* ptr,
	RustBuffer network,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_node_alias(
	void* ptr,
	RustBuffer node_alias,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_builder_set_storage_dir_path(
	void* ptr,
	RustBuffer storage_dir_path,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_free_networkgraph(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_networkgraph_channel(
	void* ptr,
	uint64_t short_channel_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_networkgraph_list_channels(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_networkgraph_list_nodes(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_networkgraph_node(
	void* ptr,
	RustBuffer node_id,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_free_node(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_node_bolt11_payment(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_node_bolt12_payment(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_close_channel(
	void* ptr,
	RustBuffer user_channel_id,
	RustBuffer counterparty_node_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_config(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_connect(
	void* ptr,
	RustBuffer node_id,
	RustBuffer address,
	int8_t persist,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_disconnect(
	void* ptr,
	RustBuffer node_id,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_event_handled(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_force_close_all_channels_without_broadcasting_txn(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_force_close_channel(
	void* ptr,
	RustBuffer user_channel_id,
	RustBuffer counterparty_node_id,
	RustBuffer reason,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_get_encoded_channel_monitors(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_list_balances(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_list_channels(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_list_payments(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_list_peers(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_listening_addresses(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_node_network_graph(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_next_event(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_node_alias(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_node_id(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_node_onchain_payment(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_open_announced_channel(
	void* ptr,
	RustBuffer node_id,
	RustBuffer address,
	uint64_t channel_amount_sats,
	RustBuffer push_to_counterparty_msat,
	RustBuffer channel_config,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_open_channel(
	void* ptr,
	RustBuffer node_id,
	RustBuffer address,
	uint64_t channel_amount_sats,
	RustBuffer push_to_counterparty_msat,
	RustBuffer channel_config,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_payment(
	void* ptr,
	RustBuffer payment_id,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_remove_payment(
	void* ptr,
	RustBuffer payment_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_sign_message(
	void* ptr,
	RustBuffer msg,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_node_spontaneous_payment(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_start(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_status(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_stop(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_sync_wallets(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_ldk_node_fn_method_node_unified_qr_payment(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_update_channel_config(
	void* ptr,
	RustBuffer user_channel_id,
	RustBuffer counterparty_node_id,
	RustBuffer channel_config,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_node_update_fee_estimates(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_ldk_node_fn_method_node_verify_signature(
	void* ptr,
	RustBuffer msg,
	RustBuffer sig,
	RustBuffer pkey,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_node_wait_next_event(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_free_onchainpayment(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_onchainpayment_new_address(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_onchainpayment_send_all_to_address(
	void* ptr,
	RustBuffer address,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_onchainpayment_send_to_address(
	void* ptr,
	RustBuffer address,
	uint64_t amount_sats,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_free_spontaneouspayment(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_spontaneouspayment_send(
	void* ptr,
	uint64_t amount_msat,
	RustBuffer node_id,
	RustBuffer sending_parameters,
	RustBuffer custom_tlvs,
	RustBuffer preimage,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_method_spontaneouspayment_send_probes(
	void* ptr,
	uint64_t amount_msat,
	RustBuffer node_id,
	RustCallStatus* out_status
);

void uniffi_ldk_node_fn_free_unifiedqrpayment(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_unifiedqrpayment_receive(
	void* ptr,
	uint64_t amount_sats,
	RustBuffer message,
	uint32_t expiry_sec,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_method_unifiedqrpayment_send(
	void* ptr,
	RustBuffer uri_str,
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_func_default_config(
	RustCallStatus* out_status
);

RustBuffer uniffi_ldk_node_fn_func_generate_entropy_mnemonic(
	RustCallStatus* out_status
);

RustBuffer ffi_ldk_node_rustbuffer_alloc(
	int32_t size,
	RustCallStatus* out_status
);

RustBuffer ffi_ldk_node_rustbuffer_from_bytes(
	ForeignBytes bytes,
	RustCallStatus* out_status
);

void ffi_ldk_node_rustbuffer_free(
	RustBuffer buf,
	RustCallStatus* out_status
);

RustBuffer ffi_ldk_node_rustbuffer_reserve(
	RustBuffer buf,
	int32_t additional,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_continuation_callback_set(
	RustFutureContinuation callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_u8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_u8(
	void* handle,
	RustCallStatus* out_status
);

uint8_t ffi_ldk_node_rust_future_complete_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_i8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_i8(
	void* handle,
	RustCallStatus* out_status
);

int8_t ffi_ldk_node_rust_future_complete_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_u16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_u16(
	void* handle,
	RustCallStatus* out_status
);

uint16_t ffi_ldk_node_rust_future_complete_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_i16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_i16(
	void* handle,
	RustCallStatus* out_status
);

int16_t ffi_ldk_node_rust_future_complete_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_u32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_u32(
	void* handle,
	RustCallStatus* out_status
);

uint32_t ffi_ldk_node_rust_future_complete_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_i32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_i32(
	void* handle,
	RustCallStatus* out_status
);

int32_t ffi_ldk_node_rust_future_complete_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_u64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_u64(
	void* handle,
	RustCallStatus* out_status
);

uint64_t ffi_ldk_node_rust_future_complete_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_i64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_i64(
	void* handle,
	RustCallStatus* out_status
);

int64_t ffi_ldk_node_rust_future_complete_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_f32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_f32(
	void* handle,
	RustCallStatus* out_status
);

float ffi_ldk_node_rust_future_complete_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_f64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_f64(
	void* handle,
	RustCallStatus* out_status
);

double ffi_ldk_node_rust_future_complete_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_pointer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_pointer(
	void* handle,
	RustCallStatus* out_status
);

void* ffi_ldk_node_rust_future_complete_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_rust_buffer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

RustBuffer ffi_ldk_node_rust_future_complete_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_poll_void(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_cancel_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_free_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_ldk_node_rust_future_complete_void(
	void* handle,
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_func_default_config(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_func_generate_entropy_mnemonic(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_claim_for_hash(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_fail_for_hash(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_receive(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_receive_for_hash(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_receive_variable_amount(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_receive_variable_amount_for_hash(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_receive_variable_amount_via_jit_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_receive_via_jit_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_send(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_send_probes(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_send_probes_using_amount(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt11payment_send_using_amount(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt12payment_initiate_refund(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt12payment_receive(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt12payment_receive_variable_amount(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt12payment_request_refund_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt12payment_send(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_bolt12payment_send_using_amount(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_build(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_build_with_fs_store(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_build_with_vss_store(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_build_with_vss_store_and_fixed_headers(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_migrate_storage(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_reset_state(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_restore_encoded_channel_monitors(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_chain_source_bitcoind_rpc(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_chain_source_esplora(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_entropy_bip39_mnemonic(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_entropy_seed_bytes(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_entropy_seed_path(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_gossip_source_p2p(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_gossip_source_rgs(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_liquidity_source_lsps2(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_listening_addresses(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_network(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_node_alias(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_builder_set_storage_dir_path(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_networkgraph_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_networkgraph_list_channels(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_networkgraph_list_nodes(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_networkgraph_node(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_bolt11_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_bolt12_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_close_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_config(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_connect(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_disconnect(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_event_handled(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_force_close_all_channels_without_broadcasting_txn(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_force_close_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_get_encoded_channel_monitors(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_list_balances(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_list_channels(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_list_payments(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_list_peers(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_listening_addresses(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_network_graph(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_next_event(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_node_alias(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_node_id(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_onchain_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_open_announced_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_open_channel(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_remove_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_sign_message(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_spontaneous_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_start(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_status(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_stop(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_sync_wallets(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_unified_qr_payment(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_update_channel_config(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_update_fee_estimates(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_verify_signature(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_node_wait_next_event(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_onchainpayment_new_address(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_onchainpayment_send_all_to_address(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_onchainpayment_send_to_address(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_spontaneouspayment_send(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_spontaneouspayment_send_probes(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_unifiedqrpayment_receive(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_method_unifiedqrpayment_send(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_constructor_builder_from_config(
	RustCallStatus* out_status
);

uint16_t uniffi_ldk_node_checksum_constructor_builder_new(
	RustCallStatus* out_status
);

uint32_t ffi_ldk_node_uniffi_contract_version(
	RustCallStatus* out_status
);



